name: "Run Tests"

on:
  workflow_dispatch:
  pull_request:
    paths:
      [
        "**.swift",
        ".github/workflows/run_tests.yml",
      ]
  push:
    branches:
      - main
    paths:
      [
        "**.swift",
        ".github/workflows/run_tests.yml",
      ]

jobs:
  run-tests:
    name: Run Tests
    runs-on: ${{ matrix.runsOn }}
    env:
      DEVELOPER_DIR: "/Applications/${{ matrix.xcode }}/Contents/Developer"
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode: "Xcode_16.app"
            runsOn: macOS-14
            name: "Xcode 16.0"
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: "swift test"
