name: "Run Tests"

on:
  workflow_dispatch:
  pull_request:
    paths:
      [
        "**Package.resolved",
        "**.swift",
        ".github/workflows/run_tests.yml",
      ]
  push:
    paths:
      [
        "**Package.resolved",
        "**.swift",
        ".github/workflows/run_tests.yml",
      ]

jobs:
  run-tests:
    name: Test ${{ matrix.os }}, Swift ${{ matrix.swift-version }}
    strategy:
      matrix:
        os: [macos-latest]
        swift-version: ["5.8", "5.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Swift ${{ matrix.swift-version }}
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}
      - name: Test
        run: "swift test"
